# Conexión a Base de Datos
spring.datasource.url=jdbc:mysql://localhost:3306/todo_app_db_test?useSSL=false&serverTimezone=UTC
spring.datasource.username=root
spring.datasource.password=

# JPA / Hibernate
spring.jpa.hibernate.ddl-auto=create
spring.jpa.defer-datasource-initialization=true
spring.sql.init.mode=always

# Thymeleaf cache (desactivar en desarrollo)
spring.thymeleaf.cache=false


# CONFIGURACIÓN DE CORREO (EMAIL)

spring.mail.host=smtp.gmail.com
spring.mail.port=587
spring.mail.username=todopro.app.noreply@gmail.com
spring.mail.password=pzbi qfow wwte cwer
spring.mail.properties.mail.smtp.auth=true
spring.mail.properties.mail.smtp.starttls.enable=true
# El nombre que aparecerá como remitente:
app.mail.from=ToDo Pro App <todopro.app.noreply@gmail.com>