# Conexión a Base de Datos MySQL local
spring.datasource.url=jdbc:mysql://localhost:3306/todo_app_db_test?useSSL=false&serverTimezone=UTC
spring.datasource.username=root
spring.datasource.password=
spring.datasource.driverClassName=com.mysql.cj.jdbc.Driver

# JPA / Hibernate
spring.jpa.database-platform=org.hibernate.dialect.MySQLDialect
spring.jpa.hibernate.ddl-auto=create-drop
spring.jpa.show-sql=true

# Forzar la carga limpia del import.sql
spring.sql.init.mode=always
spring.defer-datasource-initialization=true

# Thymeleaf cache (desactivar en desarrollo)
spring.thymeleaf.cache=false